Repository gotham-rs/gotham, pull requests merged in 2018-04, with the labels that each got.

#195 Add content type route matcher
  gotham/src/router/route/matcher/content_type.rs
  gotham/src/router/route/matcher/mod.rs
Labels: feature

#197 Switch to rustfmt shipped in stable for CI
  .travis.yml
Labels: infrastructure

#207 0.2.1 port to master
  gotham/Cargo.toml
  gotham/src/lib.rs
  gotham/src/router/non_match.rs
Labels: meta
