Repository gotham-rs/gotham, pull requests merged in 2018-03, with the labels that each got.

#178 simple async handler example
  Cargo.toml
  examples/handlers/README.md
  examples/handlers/async_handlers/README.md
  examples/handlers/simple_async_handlers/Cargo.toml
  examples/handlers/simple_async_handlers/README.md
  examples/handlers/simple_async_handlers/src/main.rs
Labels: example

#185 Correctly specify minimum dependency versions
  .travis.yml
  gotham/Cargo.toml
Labels: bug

#194 Rewrite `From<MethodSet> for Vec<Method>` impl
  gotham/src/router/non_match.rs
Labels: bug, refactor
