Repository gotham-rs/gotham, pull requests merged in 2018-02, with the labels that each got.

#137 Add Basic Path Extractor Example
  Cargo.toml
  examples/README.md
  examples/basic_path_extractor/Cargo.toml
  examples/basic_path_extractor/README.md
  examples/basic_path_extractor/src/main.rs
Labels: documentation, example

#132 Support Cookie Prefixes
  gotham/src/middleware/session/mod.rs
Labels: feature

#143 Allow route definition with different pipelines
  gotham/src/router/builder/draw.rs
Labels: feature

#144 Refactor to move the middleware chain, pipeline chain and pipeline set code to their own modules
  gotham/src/handler/mod.rs
  gotham/src/middleware/chain.rs
  gotham/src/middleware/mod.rs
  gotham/src/pipeline/chain.rs
  gotham/src/pipeline/mod.rs
  gotham/src/pipeline/set.rs
  gotham/src/pipeline/single.rs
  gotham/src/router/builder/draw.rs
  gotham/src/router/builder/mod.rs
  gotham/src/router/builder/replace.rs
  gotham/src/router/builder/single.rs
  gotham/src/router/mod.rs
  gotham/src/router/route/dispatch.rs
  gotham/src/router/route/mod.rs
  gotham/src/router/tree/mod.rs
  gotham/src/router/tree/node.rs
Labels: refactor

#147 Add the logo and cleanup main README
  README.md
  logo.svg
Labels: documentation

#149 Visibility review
  gotham/src/handler/error.rs
  gotham/src/handler/mod.rs
  gotham/src/http/header/mod.rs
  gotham/src/http/mod.rs
  gotham/src/http/request/path.rs
  gotham/src/http/request/query_string.rs
  gotham/src/http/response/mod.rs
  gotham/src/middleware/session/mod.rs
  gotham/src/middleware/session/rng.rs
  gotham/src/pipeline/mod.rs
  gotham/src/router/builder/draw.rs
  gotham/src/router/builder/mod.rs
  gotham/src/router/mod.rs
  gotham/src/router/non_match.rs
  gotham/src/router/response/extender.rs
  gotham/src/router/route/matcher/accept.rs
  gotham/src/router/route/matcher/and.rs
  gotham/src/router/route/matcher/any.rs
  gotham/src/router/route/matcher/mod.rs
  gotham/src/router/route/mod.rs
  gotham/src/router/tree/mod.rs
  gotham/src/router/tree/node.rs
  gotham/src/router/tree/regex.rs
  gotham/src/state/mod.rs
  gotham/src/state/request_id.rs
  gotham/src/test/mod.rs
  gotham_derive/src/extenders.rs
  gotham_derive/src/extractors.rs
  gotham_derive/src/helpers.rs
  gotham_derive/src/new_middleware.rs
  gotham_derive/src/state.rs
  misc/borrow_bag/src/handle.rs
Labels: refactor

#152 Setup space for handler examples
  examples/README.md
  examples/handlers/README.md
  examples/handlers/request_data/.gitkeep
Labels: documentation, example

#159 Update dependencies
  README.md
  examples/example_contribution_template/name/Cargo.toml
  examples/headers/setting/Cargo.toml
  examples/hello_world/Cargo.toml
  examples/into_response/introduction/Cargo.toml
  examples/path/introduction/Cargo.toml
  examples/query_string/introduction/Cargo.toml
  examples/routing/associations/Cargo.toml
  examples/routing/http_verbs/Cargo.toml
  examples/routing/introduction/Cargo.toml
  examples/routing/scopes/Cargo.toml
  gotham/Cargo.toml
  gotham/src/middleware/session/mod.rs
  gotham_derive/Cargo.toml
  gotham_derive/src/extenders.rs
  gotham_derive/src/helpers.rs
  gotham_derive/src/lib.rs
  gotham_derive/src/new_middleware.rs
  gotham_derive/src/state.rs
  middleware/template/Cargo.toml
  middleware/under_development/diesel/Cargo.toml
  misc/borrow_bag/Cargo.toml
Labels: refactor

#148 Add Middleware and Pipelines introduction
  Cargo.toml
  examples/README.md
  examples/example_contribution_template/name/src/main.rs
  examples/middleware/README.md
  examples/middleware/introduction/Cargo.toml
  examples/middleware/introduction/README.md
  examples/middleware/introduction/src/main.rs
Labels: documentation, example

#163 Query string split fixes
  gotham/src/http/request/query_string.rs
Labels: bug, specification
