Repository gotham-rs/gotham, pull requests merged in 2020-11, with the labels that each got.

#495 Update/Remove insecure dependencies reported by deps.rs
  examples/diesel/Cargo.toml
  examples/diesel/src/main.rs
  examples/websocket/Cargo.toml
  gotham/Cargo.toml
Labels: dependencies

#490 Remove unused mio dependency
  gotham/Cargo.toml
Labels: dependencies

#497 Avoid calling socket.peer_addr()
  gotham/src/lib.rs
Labels: bugfix

#503 Implement Into<Response> for the TestResponse
  examples/websocket/src/main.rs
  gotham/src/test.rs
Labels: feature, non-breaking-change, testing
