Repository gotham-rs/gotham, pull requests merged in 2020-09, with the labels that each got.

#465 Fix markdown
  README-dev.md
Labels: documentation

#450 Async borrowing (continuation of #449)
  examples/handlers/simple_async_handlers_await/src/main.rs
  gotham/src/handler/mod.rs
  gotham/src/router/builder/single.rs
Labels: feature, refactor

#474 Remove obsolete derive macros for PathExtractor and QueryStringExtractor
  gotham_derive/src/extractors.rs
  gotham_derive/src/lib.rs
Labels: cleanup

#475 Allow downcasting of the HandlerError's cause
  gotham/Cargo.toml
  gotham/src/handler/error.rs
Labels: feature, non-breaking-change

#476 Update the websocket example using async blocks
  examples/websocket/src/main.rs
  examples/websocket/src/ws.rs
Labels: example, non-breaking-change
