Repository gotham-rs/gotham, pull requests merged in 2021-08, with the labels that each got.

#552 Overhaul TestServer in preparation of AsyncTestServer
  gotham/src/plain/test.rs
  gotham/src/state/client_addr.rs
  gotham/src/test.rs
  gotham/src/tls.rs
  gotham/src/tls/test.rs
Labels: testing

#553 AsyncTestServer
  examples/websocket/src/main.rs
  gotham/Cargo.toml
  gotham/src/async_test.rs
  gotham/src/lib.rs
  gotham/src/plain/test.rs
  gotham/src/test.rs
  gotham/src/tls/test.rs
Labels: testing, non-breaking-change

#556 chrono: don't use default features
  gotham/Cargo.toml
Labels: dependencies, non-breaking-change
