Repository gotham-rs/gotham, pull requests merged in 2021-05, with the labels that each got.

#468 Send the state to the Session backend.
  gotham/src/middleware/session/backend/memory.rs
  gotham/src/middleware/session/backend/mod.rs
  gotham/src/middleware/session/mod.rs
Labels: breaking-change, refactor

#532 Remove hyper dependency from example
  examples/custom_service/Cargo.toml
  examples/custom_service/src/main.rs
Labels: dependencies, example, non-breaking-change

#533 Bump insecure diesel dependency
  examples/diesel/Cargo.toml
  middleware/diesel/Cargo.toml
Labels: dependencies, non-breaking-change
